config/routes.rb
Rails.application.routes.draw do

	root "users#top"
	devise_for :users
	resources :users, only: [:show, :edit, :update]
  	get "about" => "users#about"

  	resources :parties

  	resources :requests, only: [:create, :destroy, :index, :show, :new]

  	resources :chats, only: [:create, :destroy, :index, :show]

  	get "search" => "searches#search"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

	belongs_to :user
	belongs_to :room

	validates :message, presence: true, length: {maximum: 100}
end

app/models/party.rb
class Party < ApplicationRecord
	belongs_to :user
  	has_many :requests, dependent: :destroy

  	validates :place, :age, :people_count,  presence: true
  	validates :introduction, presence: true, length: {maximum: 100}
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :user
	belongs_to :party

	belongs_to :partner_user, class_name: "User"
	belongs_to :partner_party, class_name: "Party"
end

app/models/room.rb
class Room < ApplicationRecord

	has_many :user_rooms
	has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :parties
  has_many :requests

  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  validates :introduction, length: {maximum: 100}
  validates :name , presence: true
end

app/models/user_room.rb
class UserRoom < ApplicationRecord

	belongs_to :user
	belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	end

  	def after_sign_in_path_for(resource)
    user_path(current_user.id)
  	end

  	def after_sign_out_path_for(resource)
    root_path
  	end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
    @chat = Chat.new
  end

  def create
    @chat = Chat.new(chat_params)
    if @chat.save
      redirect_back(fallback_location: request.referrer)
    else
      redirect_back(fallback_location: request.referrer)
    end
  end

  def destroy
    chat = Chat.find(params[:id])
    chat.destroy
    redirect_back(fallback_location: request.referrer)
  end

  def index
    requests_for_me = Request.where(partner_user_id: current_user.id)
    my_requests = Request.where(user_id: current_user.id)
    filtered = []
    requests_for_me.each do |req|
      if my_requests.find_by(partner_user_id:req.user_id)
        filtered.push req.user
      end
    end
    @users = filtered
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :user_id, :room_id)
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :authenticate_user!

  def index
  	@parties=Party.where.not(user_id:current_user.id)
  end

  def show
    @party = Party.find(params[:id])
    @request = Request.find_by(partner_user_id:current_user.id, party_id:@party.id)
    # 各check変数を初期化
    @my_check = 1 #current_userがpartner_partyへリクエストしていない場合"１"
    @partner_check = 1 #partner_partyがcurrent_userをリクエストしていない場合"１"
    current_user.requests.each do |r|
      if r.partner_party_id == @party.id
        @my_check = 2#current_userがpartner_partyへリクエストしている場合"2"
        break
        end
      end
    @party.requests.each do |r|
      if r.partner_user_id == current_user.id
        @partner_check = 2#partner_partyがcurrent_userをリクエストしている場合"２"
        break
        end
      end
  end

  def new
  	if current_user.age.nil?
  		redirect_to user_path(current_user.id), notice: "先にプロフィール編集を行って下さい！"
  	else
  		@party=Party.new
  	end
  end

  def create
  	@party = Party.new(party_params)
  	@party.user_id=current_user.id
  	if  @party.save
		redirect_to user_path(current_user.id)
	else
		render :new
	end
  end

  def edit
  	@party = Party.find(params[:id])
  	unless current_user.id == @party.user.id
        redirect_to user_path(current_user.id)
    end
  end

  def update
  	@party = Party.find(params[:id])
  	if  @party.update(party_params)
		flash[:notice] = "パーティー情報を編集しました！"
	    redirect_to party_path(@party)
	else
	    render action: :edit
	end
  end

  def destroy
    party=Party.find(params[:id])
    requests = Request.where(partner_party_id: party.id)
    requests.each do |r|
      r.destroy
    end
    party.destroy
    redirect_to user_path(current_user.id)
  end

  private
  def party_params
  params.require(:party).permit(:place, :age, :people_count, :introduction)
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!

  def index
    requests_for_me = Request.where(partner_user_id: current_user.id)
    my_requests = Request.where(user_id: current_user.id)
    filtered = []
    requests_for_me.each do |req|
      begin
        my_requests.find_by!(partner_user_id:req.user_id)
      rescue
        filtered.push req
      end
    end
    @requests = filtered
  end

  def show
    @request = Request.find(params[:id])
  end

  def new
    if current_user.parties.count == 0
      redirect_to user_path(current_user.id), notice: "先にパーティー登録を行って下さい！"
    else
  	@party = Party.find(params[:party_id])
  	@request = Request.new
    end
  end

  def create
  	@party = Party.find(params[:request][:partner_party_id])
  	@request = Request.new(request_params)
  	@request.save
  	redirect_to party_path(@party.id)
  end

  def destroy
    @party = Party.find(params[:party_id])
  	@request = Request.find_by(user_id:current_user.id, partner_party_id:@party.id)
  	@request.destroy
  	redirect_to party_path(@party.id)
  end

  private
  def request_params
  params.require(:request).permit(:user_id, :party_id, :partner_user_id, :partner_party_id)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    users = User.where(is_gender: false)
    man_users = []
    users.each do |user|
      man_users.push user.id
    end
    @parties = Party.where.not(user_id: current_user.id)
    @parties = @parties.where("place like ?", "%#{params[:place]}%") if params[:place].present?
    @parties = @parties.where("age like ?", "%#{params[:age]}%") if params[:age].present?
    @parties = @parties.where("people_count like ?", "%#{params[:people_count]}%") if params[:people_count].present?
    @parties = @parties.where(user_id: man_users) if params[:gender] == "1"
    @parties = @parties.where.not(user_id: man_users) if params[:gender] == "2"
    render action: :search
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except:[:top, :about]

  def top
  end

  def about
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    	@user = User.find(params[:id])
    	unless current_user.id == @user.id
        redirect_to user_path(current_user.id)
      end
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = "会員情報を更新しました！"
        redirect_to user_path(@user)
      else
        render action: :edit
      end
  end

  private
	def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :age, :is_gender)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/partys_helper.rb
module PartysHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/index.html.erb
<div class="container">
	<div class="row">
		<h1><strong>チャット一覧</strong></h1>
		<% @users.each do |user| %>
			<p><%= link_to "#{user.name}",chat_path(user.id) %>さんからとのチャットページへ</p>
		<% end %>
	</div>
</div>

app/views/chats/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<h1><%= @user.name %> さんとのチャット</h1>

			<div class="message">
			  <% @chats.last(100).each do |chat| %>
			    <% if chat.user_id == current_user.id %>
			      <p style="text-align: right;"><%= chat.message %>　<%= link_to "削除する", chat_path(chat.id), method: :delete,"data-confirm" => "本当に削除しますか？" %></p>
			    <% else %>
			      <p style="text-align: left;"><%= chat.message %></p>
			    <% end %>
			  <% end %>
			</div>
			<div class="row">
				<div class="col-xs-6 col-xs-offset-3">
				<%= form_with model: @chat, url: chats_path ,local: true do |f| %>
					<%= f.hidden_field :user_id, :value => current_user.id %>
					<%= f.hidden_field :room_id, :value => @room.id %>
					<%= f.text_field :message ,placeholder:"メッセージ入力"%>
					<%= f.submit "送信する",class:"btn btn-info"%>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TogetherGo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar">
      <nav class="nav navbar-nav navbar-left">
          <%= link_to "Together-Go!", root_path %>
      </nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><span class="glyphicon glyphicon-link" aria-hidden="true"><%= link_to " About", about_path %></span></li>
          <li><span class="glyphicon glyphicon-user" aria-hidden="true"><%= link_to " Home", user_path(current_user.id) %></span></li>
          <li><span class="glyphicon glyphicon-glass" aria-hidden="true"><%= link_to " parties", parties_path %></span></li>
          <li><span class="glyphicon glyphicon-log-out" aria-hidden="true"><%= link_to " Log out", destroy_user_session_path, method: :delete %></span></li>
        <% else %>
          <li><span class="glyphicon glyphicon-link" aria-hidden="true"><%= link_to " About", about_path %></span></li>
          <li><span class="glyphicon glyphicon-edit" aria-hidden="true"><%= link_to " Sign up", new_user_registration_path %></span></li>
          <li><span class="glyphicon glyphicon-log-in" aria-hidden="true"><%= link_to " Log in", new_user_session_path %></span></li>
        <% end %>
      </ul>
    </header>

      <%= yield %>

  </body>
</html>

app/views/parties/index.html.erb
<div class="container">
    <div class="row">
    	<h1><strong>パーティー一覧</strong></h1>
    	<div class="col-xs-4">
    		<h3>[検索]</h3>
    		<div class="input-group" >
    			<%= form_with url: search_path ,local: true, method: :get do |f| %>
    				<%= f.label :gender, "性別　" %>
    				<label><%= f.radio_button :gender, 1 %>男性</label>
    				<label><%= f.radio_button :gender, 2 %>女性</label><br>
    				<%= f.label :place, "場所　" %>
    				<%= f.text_field :place %><br>
    				<%= f.label :age, "年齢　" %>
    				<%= f.text_field :age %><br>
    				<%= f.label :people_count, "人数　" %>
    				<%= f.text_field :people_count %><br>
    				<%= f.submit "検索する", class:"btn btn-primary" %>
				<% end %>
			 </div>
    	</div>
    	<div class="col-xs-8">
    		<% @parties.each do |party| %>
    			<div class="party-box">
    				<div class="row">
    					<div class="col-xs-4">
							<%= attachment_image_tag party.user, :profile_image, :fill, 150, 150, fallback: asset_path("no_image.jpg"), size:'150x150' %>
							<p><%= link_to "#{party.user.name}",user_path(party.user.id) %></p>
						</div>
						<div class="col-xs-8">
							<% if party.user.is_gender == true %>
								<p>性別　　　　　女性</p>
							<% else %>
								<p>性別　　　　　男性</p>
							<% end %>
							<p>場所　　　　　<%= party.place %></p>
							<p>年齢　　　　　<%= party.age %></p>
							<p>参加人数　　　<%= party.people_count %></p>
							<p>詳細文　　　　<%= party.introduction %></p>
							<%= link_to "パーティ詳細を見る",party_path(party.id) %>
						</div>
					</div>
    			</div>
    		<% end %>
    	</div>
    </div>
</div>

app/views/parties/new.html.erb
<div class="container">
    <div class="row">
        <% if @party.errors.any? %>
            <h3><%= @party.errors.count %>件のエラー</h3>
            <ul>
                <% @party.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        <% end %>
    	<div class="col-xs-10 col-xs-offset-2">
    		<h1><strong>パーティー登録</strong></h1>

    		<%= form_for(@party, url: parties_path) do |f| %>
    			<div class="form-group">
    				<label class="col-xs-3">性別</label>
    				<% if current_user.is_gender == true %>
    					<p>女性</p>
    				<% else %>
    					<p>男性</p>
    				<% end %>
    			</div>
    			<div class="form-group">
    				<%= f.label :"場所" ,class: "col-xs-3"%>
    				<%= f.text_field :place ,placeholder:"場所"%>
    			</div>
    			<div class="form-group">
    				<%= f.label :"年齢" ,class: "col-xs-3"%>
    				<%= f.text_field :age ,placeholder:"年齢"%>
    			</div>
    			<div class="form-group">
    				<%= f.label :"人数" ,class: "col-xs-3"%>
    				<%= f.text_field :people_count ,placeholder:"人数"%>
    			</div>
    			<div class="form-group">
    				<%= f.label :"詳細文" ,class: "col-xs-3"%>
    				<%= f.text_area :introduction ,placeholder:"詳細文"%>
    			</div>
    			<%= f.submit "登録する",class:"btn btn-info"%>
    		<% end %>
    	</div>
    </div>
</div>

app/views/parties/show.html.erb
<div class="container">
    <div class="row">
        <% if flash[:notice] %>
            <div class="flash">
                <p><%= flash[:notice] %></p>
            </div>
        <% end %>
    	<h1><strong>パーティー詳細</strong></h1>
    	<div class="col-xs-4">
    		<% if @party.user.id == current_user.id %>
                <h3>あなたのパーティーです</h3>
            <% else %>
    			<div class="request-box">
    				<% if @my_check == 1 && @partner_check == 1 %>
    					<%= form_with url: new_request_path ,local: true, method: :get do |f| %>
    						<%= f.hidden_field :party_id, :value => @party.id %>
    						<%= f.submit "リクエストする", class:"btn btn-primary" %>
    					<% end %>
    				<% elsif @my_check == 2 && @partner_check == 1 %>
    					<%= form_with url: request_path ,local: true, method: :delete do |f| %>
    						<%= f.hidden_field :party_id, :value => @party.id %>
    						<p>リクエスト中<br><%= f.submit "リクエストを取り消す", class:"btn btn-danger" %></p>
    					<% end %>
    				<% elsif @my_check == 1 && @partner_check == 2 %>
    					<%= link_to "リクエストが来ています", request_path(@request), class:"btn btn-primary" %>
    				<% else %>
    					<p>相互関係になっています<br><%= link_to "チャットページへ", chat_path(@party.user.id) %></p>
    				<% end %>
    			</div>
    		<% end %>
    	</div>
    	<div class="col-xs-8">
    		<div class="party-box">
				<div class="row">
					<div class="col-xs-4">
						<%= attachment_image_tag @party.user, :profile_image, :fill, 150, 150, fallback: asset_path("no_image.jpg"), size:'150x150' %>
						<p><%= link_to "#{@party.user.name}",user_path(@party.user.id) %></p>
					</div>
					<div class="col-xs-8">
						<% if @party.user.is_gender == true %>
							<p>性別　　　　　女性</p>
						<% else %>
							<p>性別　　　　　男性</p>
						<% end %>
						<p>場所　　　　　<%= @party.place %></p>
						<p>年齢　　　　　<%= @party.age %></p>
						<p>参加人数　　　<%= @party.people_count %></p>
						<p>詳細文　　　　<%= @party.introduction %></p>
						<% if @party.user.id == current_user.id %>
							<%= link_to "パーティーを編集する",edit_party_path%>/
							<%= link_to "パーティーを削除する", party_path, method: :delete,"data-confirm" => "本当に削除しますか？" %>
						<% end %>
					</div>
				</div>
			</div>
    	</div>
    </div>
</div>

app/views/requests/index.html.erb
<div class="container">
    <div class="row">
    	<h1><strong>受付リクエスト一覧</strong></h1>
    	<% @requests.each do |request| %>
    		<p><%= link_to "#{request.user.name}",user_path(request.user.id) %>さんからリクエストを受けています</p>
    		<p><%= link_to "リクエスト詳細ページへ", request_path(request), class:"btn btn-primary" %></p>
    	<% end %>
    </div>
</div>

app/views/requests/new.html.erb
<div class="container">
    <div class="row">
    	<h1><strong>お相手にリクエストするあなたのパーティーを選択して下さい！</strong></h1>
    	<div class="col-xs-6">
    		<div class="row">
    			<h3><strong>お相手のパーティー</strong></h3>
				<div class="col-xs-4">
					<%= attachment_image_tag @party.user, :profile_image, :fill, 115, 115, fallback: asset_path("no_image.jpg"), size:'115x115' %>
					<P><%= @party.user.name %></P>
				</div>
				<div class="col-xs-8">
		    		<% if @party.user.is_gender == true %>
						<p>性別　　　　　女性</p>
					<% else %>
						<p>性別　　　　　男性</p>
					<% end %>
					<p>場所　　　　　<%= @party.place %></p>
					<p>年齢　　　　　<%= @party.age %></p>
					<p>参加人数　　　<%= @party.people_count %></p>
					<p>詳細文　　　　<%= @party.introduction %></p>
				</div>
			</div>
    	</div>
    	<div class="col-xs-6">
    		<h3><strong>あなたのパーティー</strong></h3>
    		<%= form_with model: @request, url: requests_path ,local: true, method: :post do |f| %>
	    		<% current_user.parties.each do |party| %>
					<div class="party-box">
	    				<div class="row">
	    					<div class="col-xs-4">
	    						<%= f.radio_button :party_id, party.id %>
								<%= attachment_image_tag party.user, :profile_image, :fill, 115, 115, fallback: asset_path("no_image.jpg"), size:'115x115' %>
								<p><%= current_user.name %></p>
							</div>
							<div class="col-xs-8">
								<% if party.user.is_gender == true %>
									<p>性別　　　　　女性</p>
								<% else %>
									<p>性別　　　　　男性</p>
								<% end %>
								<p>場所　　　　　<%= party.place %></p>
								<p>年齢　　　　　<%= party.age %></p>
								<p>参加人数　　　<%= party.people_count %></p>
								<p>詳細文　　　　<%= party.introduction %></p>
							</div>
						</div>
					</div>
				<% end %>
				<%= f.hidden_field :user_id, :value => current_user.id %>
				<%= f.hidden_field :partner_user_id, :value => @party.user.id %>
				<%= f.hidden_field :partner_party_id, :value => @party.id %>
				<%= f.submit "リクエスト送信", class:"btn btn-primary" %>
			<% end %>
    	</div>
    </div>
</div>

app/views/requests/show.html.erb
<div class="container">
    <div class="row">
    	<div class="col-xs-6">
    		<div class="row">
    			<h3><strong>あなたのパーティー</strong></h3>
				<div class="col-xs-4">
					<%= attachment_image_tag @request.partner_user, :profile_image, :fill, 115, 115, fallback: asset_path("no_image.jpg"), size:'115x115' %>
					<P><%= @request.partner_user.name %></P>
				</div>
				<div class="col-xs-8">
		    		<% if @request.partner_user.is_gender == true %>
						<p>性別　　　　　女性</p>
					<% else %>
						<p>性別　　　　　男性</p>
					<% end %>
					<p>場所　　　　　<%= @request.partner_party.place %></p>
					<p>年齢　　　　　<%= @request.partner_party.age %></p>
					<p>参加人数　　　<%= @request.partner_party.people_count %></p>
					<p>詳細文　　　　<%= @request.partner_party.introduction %></p>
				</div>
			</div>
		</div>
		<div class="col-xs-6">
			<div class="row">
				<h3><strong>お相手のパーティー</strong></h3>
				<div class="col-xs-4">
					<%= attachment_image_tag @request.user, :profile_image, :fill, 115, 115, fallback: asset_path("no_image.jpg"), size:'115x115' %>
					<P><%= link_to "#{@request.user.name}",user_path(@request.user.id) %></P>
				</div>
				<div class="col-xs-8">
		    		<% if @request.user.is_gender == true %>
						<p>性別　　　　　女性</p>
					<% else %>
						<p>性別　　　　　男性</p>
					<% end %>
					<p>場所　　　　　<%= @request.party.place %></p>
					<p>年齢　　　　　<%= @request.party.age %></p>
					<p>参加人数　　　<%= @request.party.people_count %></p>
					<p>詳細文　　　　<%= @request.party.introduction %></p>
				</div>
				<%= form_with model: @request, url: requests_path ,local: true, method: :post do |f| %>
					<%= f.hidden_field :user_id, :value => current_user.id %>
					<%= f.hidden_field :party_id, :value => @request.partner_party.id %>
					<%= f.hidden_field :partner_user_id, :value => @request.user.id %>
					<%= f.hidden_field :partner_party_id, :value => @request.party.id %>
					<%= f.submit "リクエストを許可する", class:"btn btn-primary" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/searches/search.html.erb
<div class="container">
    <div class="row">
    	<h1><strong>パーティー一覧</strong></h1>
    	<div class="col-xs-4">
    		<h3>[検索]</h3>
    		<div class="input-group" >
    			<%= form_with url: search_path ,local: true, method: :get do |f| %>
    				<%= f.label :gender, "性別　" %>
    				<label><%= f.radio_button :gender, 1 %>男性</label>
    				<label><%= f.radio_button :gender, 2 %>女性</label><br>
    				<%= f.label :place, "場所　" %>
    				<%= f.text_field :place %><br>
    				<%= f.label :age, "年齢　" %>
    				<%= f.text_field :age %><br>
    				<%= f.label :people_count, "人数　" %>
    				<%= f.text_field :people_count %><br>
    				<%= f.submit "検索する", class:"btn btn-primary" %>
				<% end %>
			 </div>
    	</div>
    	<div class="col-xs-8">
    		<% @parties.each do |party| %>
    			<div class="party-box">
    				<div class="row">
    					<div class="col-xs-4">
							<%= attachment_image_tag party.user, :profile_image, :fill, 150, 150, fallback: "no_image.jpg", size:'150x150' %>
							<p><%= link_to "#{party.user.name}",user_path(party.user.id) %></p>
						</div>
						<div class="col-xs-8">
							<% if party.user.is_gender == true %>
								<p>性別　　　　　女性</p>
							<% else %>
								<p>性別　　　　　男性</p>
							<% end %>
							<p>場所　　　　　<%= party.place %></p>
							<p>年齢　　　　　<%= party.age %></p>
							<p>参加人数　　　<%= party.people_count %></p>
							<p>詳細文　　　　<%= party.introduction %></p>
							<%= link_to "パーティ詳細を見る",party_path(party.id) %>
						</div>
					</div>
    			</div>
    		<% end %>
    	</div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<% if flash[:notice] %>
  			<div class="flash">
    			<p><%= flash[:notice] %></p>
  			</div>
		<% end %>
		<% if @user.id == current_user.id %>
			<h3><strong>あなたのホーム</strong></h3>
		<% else %>
			<h3><strong><%= @user.name %>さんのホーム</strong></h3>
		<% end %>
		<div class="col-xs-4">
			<div class="profile">
				<%= attachment_image_tag @user, :profile_image, :fill, 150, 150, fallback: asset_path("no_image.jpg"), size:'150x150' %>
				<p>名前　　　　<%= @user.name %></p>
				<% if @user.is_gender == true %>
					<p>性別　　　　女性</p>
				<% else %>
					<p>性別　　　　男性</p>
				<% end %>
				<p>年齢　　　　<%= @user.age %></p>
				<p>自己紹介　　<%= @user.introduction %></p>
				<% if @user.id == current_user.id %>
					<%= link_to "プロフィールを編集する",edit_user_path, class:"btn btn-primary" %>
				<% end %>
			</div>
			<div class="links">
				<% if @user.id == current_user.id %>
					<p><%= link_to "＜パーティーを登録する＞",new_party_path %></p>
					<p><%= link_to "＜パーティー相手を探す＞",parties_path %></p>
					<p><%= link_to "＜受付リクエスト一覧＞",requests_path %></p>
					<p><%= link_to "＜チャット一覧＞",chats_path %></p>
				<% end %>
			</div>
		</div>
		<div class="col-xs-8">
			<% if @user.id == current_user.id %>
				<h4><strong>あなたのパーティー一覧</strong></h4>
			<% else %>
				<h4><strong><%= @user.name %>さんのパーティー一覧</strong></h4>
			<% end %>
			<% @user.parties.each do |party| %>
				<div class="party-box">
    				<div class="row">
    					<div class="col-xs-4">
							<%= attachment_image_tag party.user, :profile_image, :fill, 150, 150, fallback: asset_path("no_image.jpg"), size:'150x150' %>
							<p><%= @user.name %></p>
						</div>
						<div class="col-xs-8">
							<% if party.user.is_gender == true %>
								<p>性別　　　　　女性</p>
							<% else %>
								<p>性別　　　　　男性</p>
							<% end %>
							<p>場所　　　　　<%= party.place %></p>
							<p>年齢　　　　　<%= party.age %></p>
							<p>参加人数　　　<%= party.people_count %></p>
							<p>詳細文　　　　<%= party.introduction %></p>
							<%= link_to "パーティ詳細を見る",party_path(party.id) %>
						</div>
					</div>
    			</div>
    		<% end %>
		</div>
	</div>
</div>